Documentation:
  - docs/
  - README.md

Deployment:
  - pkg/
  - .github/scripts/build-pex-bundle.sh
  - .github/workflows/publish-version.yaml
  - entrypoint.py
    
Core Functionality:
  - bolt/core/*
  - bolt/utils/*
  - bolt/data/*
  - bolt/bot.py
    
Discord Connector:
  - bolt/discord/*
  - bolt/discord/**/*
    
Tests:
  - tests/*
  - tests/**/*
