repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: flake8
