name: Deploy Doc Site
on:
  push:
    paths:
    - 'docs/**'

jobs:
  build-docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lektor
        gem install sass
    
    - name: Compile SCSS
      run: |
        scss --style=compressed docs/scss/milligram.scss > docs/assets/static/milligram.min.css
    
    - name: Lektor Build
      run: |
        pushd docs
        lektor build
        popd
    
    - name: Lektor Deploy
      if: github.event_name != 'pull_request' && github.ref == 'master'
      run: |
        pushd docs
        lektor deploy ghpages
        popd
