name: Pull Request
on: [pull_request]

jobs:
  run-linter:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r REQUIREMENTS.txt

    - name: Linting...
      run: |
        flake8 bolt/

  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install nose
        pip install -r REQUIREMENTS.txt

    - name: Testing...
      run: |
        nosetests -w tests/

  build-docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lektor
        gem install sass
    
    - name: Compile SCSS
      run: |
        scss --style=compressed docs/scss/milligram.scss > docs/assets/static/milligram.min.css
    
    - name: Lektor Build
      run: |
        pushd docs
        lektor build
        popd
    
